language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1

env:
  - PHP_BIN=php
  - PHP_BIN=php-cgi

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --optimize-autoloader --prefer-dist
  - tests/travis.phpredis.sh

before_script:
  - ./vendor/bin/parallel-lint -e php,phpt --exclude vendor .
  - ./vendor/bin/phpstan analyze --no-progress -l 5 -c ./phpstan.neon ./

script:
  - ./vendor/bin/tester -s -p $PHP_BIN -j 32 ./tests/CriticalSectionTests

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
