os: linux 
dist: xenial
language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

services:
  - redis

env:
  - PHP_BIN=php
  - PHP_BIN=php-cgi

before_install:
  - travis_retry composer self-update --2

addons:
  apt:
    packages:
      - redis-server

install:
  - travis_retry composer install --no-interaction --optimize-autoloader --prefer-dist
  - tests/travis.phpredis.sh

script:
  - ./vendor/bin/tester -s -p $PHP_BIN -c ./tests/php.ini-unix -j 32 ./tests/CriticalSectionTests


jobs:
  include:
  - stage: Parallel Lint
    php: 7.4
    script:
    - composer self-update --2
    - composer run-script php-parallel-lint-install
    - composer run-script php-parallel-lint

  - stage: Code Checker
    php: 7.4
    script:
    - composer self-update --2
    - composer run-script code-checker-install
    - composer run-script code-checker

  - stage: Phpstan
    php: 7.4
    script:
    - composer self-update --2
    - composer run-script phpstan-install
    - composer run-script phpstan

  - stage: Test Coverage
    php: 7.4
    script:
    - composer self-update --2
    - composer run-script coverage

  allow_failures:
  - stage: Parallel Lint
  - stage: Code Checker
  - stage: Test Coverage
  - stage: Phpstan


after_failure:
  -  for i in $(find   tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done


cache:
  directories:
    - $HOME/.composer/cache
